In [1]:
import numpy as np

In [2]:
pi_0 = np.array([0.40, 0.35, 0.20, 0.05])

In [3]:
P = np.array([
    [0.85, 0.06, 0.07, 0.02],
    [0.08, 0.80, 0.10, 0.02],
    [0.10, 0.10, 0.75, 0.05],
    [0.12, 0.10, 0.08, 0.70]
])

In [4]:
pi_1 = np.dot(pi_0, P)
print("Market shares for period 1:")
print(pi_1)

Market shares for period 1:
[0.394 0.329 0.217 0.06 ]


In [5]:
pi_2_from_1 = np.dot(pi_1, P)
print('Market shares for period 2 given period 1:')
print(pi_2_from_1)

Market shares for period 2 given period 1:
[0.39012 0.31454 0.22803 0.06731]


In [6]:
P2 = np.dot(P, P)
print(P2)

[[0.7367 0.108  0.1196 0.0357]
 [0.1444 0.6568 0.1622 0.0366]
 [0.174  0.166  0.5835 0.0765]
 [0.202  0.1652 0.1344 0.4984]]


In [7]:
pi_2_direct = np.dot(pi_0, P2)
print('Market shares for period 2 given period 0:')
print(pi_2_direct)

Market shares for period 2 given period 0:
[0.39012 0.31454 0.22803 0.06731]


In [8]:
pi_0 = np.array([1, 0])

In [9]:
P = np.array([
    [0.90, 0.10],
    [0.20, 0.80]
])

In [10]:
n_periods = 20

In [11]:
state_probabilities = [pi_0]

In [12]:
for _ in range(n_periods):
    pi_next = np.dot(state_probabilities[-1], P)
    state_probabilities.append(pi_next)

In [13]:
for i, pi in enumerate(state_probabilities):
    print(f'Period {i} = {pi}')

Period 0 = [1 0]
Period 1 = [0.9 0.1]
Period 2 = [0.83 0.17]
Period 3 = [0.781 0.219]
Period 4 = [0.7467 0.2533]
Period 5 = [0.72269 0.27731]
Period 6 = [0.705883 0.294117]
Period 7 = [0.6941181 0.3058819]
Period 8 = [0.68588267 0.31411733]
Period 9 = [0.68011787 0.31988213]
Period 10 = [0.67608251 0.32391749]
Period 11 = [0.67325776 0.32674224]
Period 12 = [0.67128043 0.32871957]
Period 13 = [0.6698963 0.3301037]
Period 14 = [0.66892741 0.33107259]
Period 15 = [0.66824919 0.33175081]
Period 16 = [0.66777443 0.33222557]
Period 17 = [0.6674421 0.3325579]
Period 18 = [0.66720947 0.33279053]
Period 19 = [0.66704663 0.33295337]
Period 20 = [0.66693264 0.33306736]


In [14]:
pi_0 = np.array([1, 0])

In [15]:
P = np.array([
    [0.80, 0.20],
    [0.10, 0.90]
])

In [16]:
n_periods = 20

In [17]:
state_probablities = [pi_0]

In [18]:
for _ in range(n_periods):
    pi_next = np.dot(state_probabilities[-1], P)
    state_probabilities.append(pi_next)

In [19]:
for i, pi in enumerate(state_probabilities):
    print(f'Period {i} = {pi}')

Period 0 = [1 0]
Period 1 = [0.9 0.1]
Period 2 = [0.83 0.17]
Period 3 = [0.781 0.219]
Period 4 = [0.7467 0.2533]
Period 5 = [0.72269 0.27731]
Period 6 = [0.705883 0.294117]
Period 7 = [0.6941181 0.3058819]
Period 8 = [0.68588267 0.31411733]
Period 9 = [0.68011787 0.31988213]
Period 10 = [0.67608251 0.32391749]
Period 11 = [0.67325776 0.32674224]
Period 12 = [0.67128043 0.32871957]
Period 13 = [0.6698963 0.3301037]
Period 14 = [0.66892741 0.33107259]
Period 15 = [0.66824919 0.33175081]
Period 16 = [0.66777443 0.33222557]
Period 17 = [0.6674421 0.3325579]
Period 18 = [0.66720947 0.33279053]
Period 19 = [0.66704663 0.33295337]
Period 20 = [0.66693264 0.33306736]
Period 21 = [0.56685285 0.43314715]
Period 22 = [0.49679699 0.50320301]
Period 23 = [0.4477579 0.5522421]
Period 24 = [0.41343053 0.58656947]
Period 25 = [0.38940137 0.61059863]
Period 26 = [0.37258096 0.62741904]
Period 27 = [0.36080667 0.63919333]
Period 28 = [0.35256467 0.64743533]
Period 29 = [0.34679527 0.65320473]
Period 30 

In [20]:
P = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0.80, 0, 0.10, 0.10],
    [0.30, 0.10, 0.30, 0.30]
])

In [21]:
I = np.array([
    [1, 0],
    [0, 1]
])

In [22]:
A = np.array([
    [0.80, 0],
    [0.30, 0.10]
])

In [23]:
B = np.array([
    [0.10, 0.10],
    [0.30, 0.30]
])

In [24]:
I_minus_B = I - B
F = np.linalg.inv(I_minus_B)

FA = np.dot(F, A)

print('The final matrix FA is:')
print(FA)

The final matrix FA is:
[[0.98333333 0.01666667]
 [0.85       0.15      ]]
